name: 💡 Requisição de Tarefa
description: Levantamento de tarefas a serem realizadas durante o projeto.
title: 'TAREFA: '
body:

  - type: textarea
    id: description
    attributes:
      label: Descrição da tarefa
      description: Nesse campo deve-se preencher as especificações da tarefa.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Descrição dos casos de uso
      description: Descrever oque essa tarefa vai solucionar.
    validations:
      required: true
      
  - type: textarea
    id: requirement
    attributes:
      label: Requisitos atendidos
      description: Preencher com o requisito principal e suas referências.
    validations:
      required: true

  - type: textarea
    id: business-rule
    attributes:
      label: Regra de negócio
      description: Preencher a regra de negócio que deverá ser levada em consideração.
    validations:
      required: true
      
  - type: textarea
    id: proposed-solution
    attributes:
      label: Suguestão de solução
      description: Descrever uma ideia previa de como realizará a tarefa.

    id: additional-information
    attributes:
      label: Observações
      description: Se for o caso, alguma observação que deve ser levada em consideração para realização da tarefa.
